component: website
name: website-293G387j0x
org: '1258675557'
app: static-website
stage: dev
inputs:
  region: ap-guangzhou
  src:
    error: index.html
    exclude:
      - .env
    index: index.html
    src: ./
  bucketName: static-website
  isAutoCiDeploy: true
  codePlatform: GITHUB
  gitUrl: 'https://github.com/daaihang/daaihang.github.io.git'
  branch: gh-pages
